name: Ansible Lint

on: [push, pull_request]

jobs:
  ansible-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Ansible Lint Action
      uses: ansible/ansible-lint@v6
