---
name: Ansible Lint - sap_software_download

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_software_download/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'roles/sap_software_download/**'

  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

        # Use @v25 to automatically track the latest release from the year 2025.
        # ansible-lint uses Calendar Versioning (e.g., v25.9.0 -> YYYY.MM.PATCH).
        # Avoid using @main, which can introduce breaking changes unexpectedly.
      - uses: ansible/ansible-lint@v25
        with:
          # v25.7.0 no longer uses 'working_directory' and role path is set in 'args'.
          # Role specific .ansible-lint can be added with argument '-c'.
          args: roles/sap_software_download
          # Use the shared requirements file from the collection root for dependency context.
          requirements_file: ./requirements.yml
