# SPDX-License-Identifier: Apache-2.0
---

# Variables specific to following versions:
# - SUSE Linux Enterprise Server 15

# NOTE: SLES 15 SP5 introduced Python 3.11.

# Set which Python version will be used on destination node.
# This is python executable name, which can differ from python package name.
__sap_software_download_python_interpreter: >-
  {%- if ansible_distribution_version.split('.')[1] | int < 5 -%}
    python3
  {%- else -%}
    python3.11
  {%- endif -%}

# Set which Python package will be installed on destination node.
__sap_software_download_python_package: >-
  {%- if ansible_distribution_version.split('.')[1] | int < 5 -%}
    python3
  {%- else -%}
    python311
  {%- endif -%}

# The list of required Python Modules in packages
# This is required in order to avoid externally-managed-environment error.
__sap_software_download_python_module_packages:
    "{{ __sap_software_download_python_module_packages_3
      if ansible_distribution_version.split('.')[1] | int < 5
      else __sap_software_download_python_module_packages_311 }}"

# The lists of Python Modules for specific python version
__sap_software_download_python_module_packages_3:
  - "python3-wheel"
  - "python3-urllib3"
  - "python3-requests"
  - "python3-beautifulsoup4"
  - "python3-lxml"

__sap_software_download_python_module_packages_311:
  - "python311-wheel"
  - "python311-urllib3"
  - "python311-requests"
  - "python311-beautifulsoup4"
  - "python311-lxml"
